### ISSUE TITLE
'Save' does not save which channels to record

### ISSUE THREAD

**Issue by galenlynch** [open-ephys/plugin-GUI#128]
My understanding of the "save..." menu item is to save the current state of the gui (signal chain, processor configuration, etc) so it can be easily restored later. 

However, if I edit which channels to record with the rhythm FPGA processor and then either use "save..." or "save as...", these edits will not be applied when I next open the GUI and use the "open..." menu item. 

I'm using Windows.

**Comment by ethanbb** [comment]
This issue appears to be fixed in the current development branch - are you still having the problem?
