### ISSUE TITLE
unable to load settings with selected recording channels OEv2 acquisition board

### ISSUE THREAD

**Issue by lepmik** [open-ephys/plugin-GUI#131]
When saving a signal chain with only a few selected recording channels the gui crashes after loading it and starting acquisition. Unable to get any clue to the reason as the gui freezes completely.

Windows 7 enterprise
Visual studio 13 release 64 build
usb3 cable in ss slot to acquisition sys

**Comment by lepmik** [comment]
In addition it is crashing when loading a settings file with deselected TTL channels in the LFP viewer.

**Comment by ethanbb** [comment]
I can't replicate this (using USB2). Is it still happening for you with the latest release?

**Comment by jsiegle** [comment]
This is no longer relevant, now that the recording settings all live in the Record Node (rather than individual plugins).
