### ISSUE TITLE
GUI Crash on adding audio channel in FPGA module (OSX)

### ISSUE THREAD

**Issue by shayo** [open-ephys/plugin-GUI#137]
New chain => Drag Rhythm => Click Run => Open drawer => click on "1" audio channel => crash

 ChannelSelectorButton* b = (ChannelSelectorButton*)button;

        if (b->getType() == AUDIO)
        {
            // get audio node, and inform it of the change
            GenericEditor* editor = (GenericEditor*)getParentComponent();

            const DataChannel* ch = editor->getChannel(b->getChannel() - 1);
            //int channelNum = editor->getStartChannel() + b->getChannel() - 1;
            bool status = b->getToggleState();
------
  crashing because b returns null ?!?

**Comment by jsiegle** [comment]
This should be fixed, now, but if you're still experiencing this problem with the latest version of the GUI, please open an issue in the new [Rhythm Plugins](https://github.com/open-ephys-plugins/rhythm-plugins) repository.
