### ISSUE TITLE
Extracting sample rate from settings.xml

### ISSUE THREAD

**Issue by malfatti** [open-ephys/plugin-GUI#144]
Hello!

I'm trying to get the sample rate used in recording from the settings.xml file. At `/SETTINGS/SIGNALCHAIN/PROCESSOR/EDITOR/SampleRate` I'm getting "17" for 30kHz recs. Is there a way to extract the sample rate used in recording from the settings.xml file?

Cheers :)

**Comment by angelonc** [comment]
Bumping this because I'm having the same issue as well!

**Comment by jsiegle** [comment]
I just pushed an update to the `development` branch that outputs the sample rate as a string to the settings.xml file. "17" refers to the index of the selected sample rate in the dropdown menu, which is required to re-load the previous settings, but is not very helpful for figuring out what the sample rate actually was.
