### ISSUE TITLE
timestamp before clicking play bug

### ISSUE THREAD

**Issue by shayo** [open-ephys/plugin-GUI#152]
Please consider the following:

```

int64 MessageCenter::getTimestamp(bool softwareTime)
{
	**if (timestampSource == nullptr)
		return 0;**

    if (!softwareTime && sourceNodeId > 0)
        return timestampSource->getTimestamp(0);
    else
        return (softTimestamp);
}

```
right now, when a module is trying to call CoreServices::getTimestamp() before play is pressed, there is a crash because timestampSource is not yet initialized.

**Comment by jsiegle** [comment]
The Message Center has been substantially reworked in the latest version of the GUI. Now, it broadcasts messages to every data stream, which apply their local timestamps to the messages. So this segment of code is no longer relevant.
