### ISSUE TITLE
LFP Viewer drawing bug

### ISSUE THREAD

**Issue by shayo** [open-ephys/plugin-GUI#153]
I'm still experiencing drawing issues with LFP Viewer (TTL events are not drawn correctly):
![image](https://user-images.githubusercontent.com/1977614/28796980-a0062f72-760d-11e7-8147-cd637db6ae3e.png)

**Comment by jvoigts** [comment]
this is fairly old code so i don't think it will make a difference, but just to be sure, could you try the lfp viewer beta?

**Comment by shayo** [comment]
Looks slightly better, but still same issue.
![image](https://user-images.githubusercontent.com/1977614/28797733-4cabd874-7610-11e7-8456-b356bb6ad8ff.png)

**Comment by pbaker2** [comment]
We are having a similar issue, after about 3 minutes of recording, our events get really messy on the LFP viewer. Additionally, it will occasionally start leaving an event channel in the high position (when using a gate) which is really bad when using the arduino output to a laser. I'm guessing that it has something to do with the event channels backing up in a buffer or something but the CPU meter on the GUI isn't really suggesting that it should be bogging down. I'm no expert in the data stream though so I may be missing something. Any insight into this?
