### ISSUE TITLE
Urgent: incorrect timestamps when reading ADC continuous channel

### ISSUE THREAD

**Issue by shayo** [open-ephys/plugin-GUI#154]
I've done a short test recording of a photodiode signal (to make sure things are properly synchronized in my rig). 
I observed weird and non-expected behavior when looking at the timestamps returned from load_open_ephys_data_faster.

When parsing the continuous file, nsamples are all 1024. Plotting  info.ts looks good on the surface:

![image](https://user-images.githubusercontent.com/1977614/28797275-c19b89ec-760e-11e7-811f-1349350c7eb1.png)

But when I look more carefully (plot diff), I get the following:
![image](https://user-images.githubusercontent.com/1977614/28797343-03646b6e-760f-11e7-876f-ae16fea6a132.png)

This doesn't look right.
Also, when I plot the signal, aligned to these timestamps, it artificially stretches some intervals:
![image](https://user-images.githubusercontent.com/1977614/28797424-3dd4931e-760f-11e7-92e8-6188f9d7d560.png)

I can hookup a signal generator, but I'm pretty sure I'll also see a skewed sine wave.
For reference, here is the same data, plotted without the timestamps (i.e., assuming fixed sampling rate):

![image](https://user-images.githubusercontent.com/1977614/28797463-6800c02c-760f-11e7-81af-f6e30cf163dc.png)

This data was from an ADC channel.
Looking at another channel (ch1 - spike), diff returns a perfect 1024.

This may or may not be related to the other issue I found today. As a side note - this recorded session was not paused or resumed.

**Comment by shayo** [comment]
FYI: @aacuevas , @jsiegle , @jvoigts 
This goes away when I record all channels, so this is probably related to the other bug that I reported.
I'm guessing the index increment is incorrect in RHD2000Thread::updateBuffer() ?!?!?

**Comment by aacuevas** [comment]
I'm inclined to think the issue is in the recording part, since the number of recorded channels is irrelevant to the hardware buffers. But it might very well be related

**Comment by shayo** [comment]
Recent patch to OriginalRecording solved the issue.
