### ISSUE TITLE
TTL Timestamp

### ISSUE THREAD

**Issue by shayo** [open-ephys/plugin-GUI#156]
@aacuevas , Are TTL timestamps encoded in the TTL midi message, or should I look at the last TIMESTAMP message that was received and add SampleNum to get the actual timestamp of the event?

**Comment by aacuevas** [comment]
In the old system you need to look at the last TIMESTAMP message and add sampleNum indeed. In the new system the timestamp is available from the TTLEvent object.

**Comment by shayo** [comment]
OK. As I thought. Thank you for the clarification.
