### ISSUE TITLE
Loss of data durcing transmission when using ofSerial interface

### ISSUE THREAD

**Issue by FlorianFranzen** [open-ephys/plugin-GUI#163]
I had some issues with the ofSerial class shipped with the OpenEphys, where random bytes would just not be transmitted. 

As it is based on an old version of openFramework, I update the offending files, and my problem went away. I tried to bisect the problem a little bit, but I could not really pin down, what fixed the issue for me.

I assume it has to do with some of the flags that have been added over time, so a potential patch for ```ofSerial::setup(...)``` could look something like this:
```patch
		options.c_cflag |= (CLOCAL | CREAD);
		options.c_cflag &= ~PARENB;
		options.c_cflag &= ~CSTOPB;
		options.c_cflag &= ~CSIZE;
+		options.c_iflag &= (tcflag_t) ~(INLCR | IGNCR | ICRNL | IGNBRK);
+		options.c_oflag &= (tcflag_t) ~(OPOST);
		options.c_cflag |= CS8;
+		#if defined( TARGET_LINUX )
+			options.c_cflag |= CRTSCTS;
+			options.c_lflag &= ~(ICANON | ECHO | ISIG);
+		#endif
		tcsetattr(fd, TCSANOW, &options);
+		#ifdef TARGET_LINUX
+			struct serial_struct kernel_serial_settings;
+			if (ioctl(fd, TIOCGSERIAL, &kernel_serial_settings) == 0) {
+				kernel_serial_settings.flags |= ASYNC_LOW_LATENCY;
+				ioctl(fd, TIOCSSERIAL, &kernel_serial_settings);
+			}
+		#endif
```

I currently lack the time to create a proper pull request, so I thought I at least document that there is a problem and a potential fix.

**Comment by jsiegle** [comment]
The recommended changes have been incorporated into the `ofSerial.cpp` source code.
