### ISSUE TITLE
Testing 0.4.3 : no debug64 version? 

### ISSUE THREAD

**Issue by vncntprvst** [open-ephys/plugin-GUI#171]
Hi everyone,
I tried compiling the new version (0.4.3) on Windows. The Debug works fine (although there are issues with plugin compilation later on), but Debug64 fails, saying that it can't find the path specified. 
![image](https://user-images.githubusercontent.com/1872756/32463343-92a0193e-c30a-11e7-9d2d-1965b8bb4f12.png)
Is there no debug64 version? 
Thanks
Vincent

**Comment by vncntprvst** [comment]
Related to this issue: when compiling plugins, x64 version are not available, and fail as expected:
![image](https://user-images.githubusercontent.com/1872756/32463708-859390d0-c30b-11e7-9629-7baab36636cd.png)
However, even setting the plugin project to Debug / Win32 in Visual Studio's Configuration manager, there are errors: 
![image](https://user-images.githubusercontent.com/1872756/32463816-dc5ad216-c30b-11e7-9fc9-dd985d10b7f3.png)

**Comment by aacuevas** [comment]
Please, check that the architecture selector (just at the right of the Release/Debug selector) is set to x64 when compiling the Debug64 version.

Also, you won't be able to start the GUI from the plugins project, that's normal.

**Comment by vncntprvst** [comment]
OK, thanks. My bad. There's no architecture selector in the menu bar (at least by default), it's in the Configuration Manager and I had forgotten to check that - I don't compile stuff very often. The GUI works now. 
![oev043](https://user-images.githubusercontent.com/1872756/32466981-ef25474a-c316-11e7-94bf-1c3429a4be71.png). 
Only thing is, it crashes when I try to monitor the audio signal. I might have missed something in the compilation.
