### ISSUE TITLE
Resizing application window can cause screen display problems on Windows 10

### ISSUE THREAD

**Issue by kmichaelfox** [open-ephys/plugin-GUI#172]
There is some kind of issue going on the testing branch with a Windows 10 VS2015 build, where resizing the window occasionally locks the application's screen updates until it is resized again. During this time, GUI elements on screen can still be interacted with. Modal tooltips will appear, but when they are removed the screen space under them reverts to the out-of-date screen display image.

It is a little difficult to correlate the behavior with specific actions, but it seems tied to resizing the window too quickly.

I was not able to replicate this behavior with X11 or Cocoa windows.

**Comment by anjaldoshi** [comment]
Not reproducible in the latest version of the GUI. Reopen if encountered again.
