### ISSUE TITLE
Processors drawer exhibits resizing problems when window width is sufficiently small

### ISSUE THREAD

**Issue by kmichaelfox** [open-ephys/plugin-GUI#176]
The contents of the Processors drawer spills out of it's component container when the window is close to its minimum width.

For most window sizes, resizing the width causes the canvas area to stretch with minimal impact to either the Signal Chain or Processors drawer. After decreasing the width beyond a certain point, the canvas area attempts to maintain a fixed width and begins to displace the Processors drawer off the screen to the left if it is open. After this threshold, the Processors drawer overrides its height constraints as well, causing it to drawn outside of the intended bounds.

This behavior is exhibited both with the Signal Chain drawer open or closed.

Before reaching width threshold:
![processor-drawer1](https://user-images.githubusercontent.com/5326225/32469914-b6b452d2-c309-11e7-9526-ef3074eccd8a.png)

After passing width threshold, Signal Chain drawer open:
![processor-drawer2](https://user-images.githubusercontent.com/5326225/32469918-be200610-c309-11e7-979a-1916ea46477b.png)

After passing width threshold, Signal Chain drawer closed:
![processor-drawer3](https://user-images.githubusercontent.com/5326225/32469922-c0de1112-c309-11e7-9969-9e84b62a19cd.png)

**Comment by aacuevas** [comment]
Well, resizing beyond a certain point did cause other issues too, so I've increased the minimum window size. I'm not getting this or other issues now. Of course, this does not apply to Linux, due to #177

**Comment by kmichaelfox** [comment]
Clamping the window's width to a minimum of 484 solved this problem for me on all three platforms. #179 solves this issue for linux on Debian 9.2.1.
