### ISSUE TITLE
X11 application windows fail to enforce minimum window dimensions

### ISSUE THREAD

**Issue by kmichaelfox** [open-ephys/plugin-GUI#177]
Testing branch built with GCC 6 on Debian 9.2.1, with Xorg 1.19 does not maintain a minimum window size. I feel that it would be worthwhile to try enforcing this manually.

**Comment by aacuevas** [comment]
It seems to be a shortcoming of the JUCE library that doesn't seem to be fixed yet ( https://forum.juce.com/t/linux-setresizelimits/13026/3 last post 14 days ago).

I'm not sure I know how to enforce manually without having to mess with Juce code itself, though. I'll look into it.
