### ISSUE TITLE
Selected reference channel is not saved

### ISSUE THREAD

**Issue by jonnew** [open-ephys/plugin-GUI#199]
OS: Ubuntu 16.04
Version: 8406ede366ef025c8754f17e56eb52510739524e

When I save a OE GUI settings file, and reload it, the previously selected reference channel (in 
"param" section of the Channel Map component) is no longer selected or applied.

**Comment by ethanbb** [comment]
Closed by #221 (I don't have the permission to close this but it should be fixed)

**Comment by jsiegle** [comment]
The Channel Map plugin no longer includes a digital referencing option. Instead, we recommend using the Common Average Reference plugin, which should save/load all settings exactly as they were when the GUI was closed.
