### ISSUE TITLE
TTL Settle Channel won't set to values greater than 2

### ISSUE THREAD

**Issue by PaulMAnderson** [open-ephys/plugin-GUI#200]
We started using the TTL settle function recently and have noticed a strange bug. 

Setting the channel to trigger the settle works fine for off, TTL1 or TTL2, but selecting any higher channel doesn't actually change the channel triggering the amps to settle. They are continually triggered by channel 2 when it is set to channels 3 through 8.

This is on a Windows 7 computer running the latest binary download version of open-ephys.

**Comment by jsiegle** [comment]
The plugin for interfacing with the acquisition board now lives here: https://github.com/open-ephys-plugins/rhythm-plugins

If you're still experiencing this problem with the latest version of the GUI, please open an issue in that repository.
