### ISSUE TITLE
"Rename files" option for Open Ephys format is broken

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/plugin-GUI#204]
Well, the actual renaming part (changing "CH" to your string of choice) works. But when the option is selected, the name is calculated by this code in OriginalRecording.cpp (starting at line 258):

```    
String filename;
const DataChannel* ch = getDataChannel(channelIndex);

filename += String(static_cast<int>(ch->getCurrentNodeID()));
filename += "_";
if (renameFiles)
    filename += renamedPrefix + String(originalChannelIndexes[channelIndex] + 1);
```

However, it doesn't look like `originalChannelIndexes` actually contains anything. It's cleared in `resetChannels`, but it's not changed anywhere else. So what ends up happening is line 264 indexes into an empty array, happens to find a 0 (when I was testing it), and ends up writing to the same file, "...`renamedPrefix`1.continuous", for each channel. The result is a corrupted file if there is more than one channel.

Suggested fix: remove this feature since it doesn't seem very useful and also makes it harder to tell regular, aux and adc channels apart.

**Comment by jsiegle** [comment]
The file renaming feature for the Open Ephys format has been removed -- the file names are now based on the processor ID, stream, and name of the associated continuous channel.
