### ISSUE TITLE
Disabling channels in LFP viewer doesn't persist

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/plugin-GUI#208]
The new LFP viewer has a bug where the following actions cause channels that have been disabled (i.e. drawing turned off) become re-enabled:

* Zooming in on a single channel and zooming back out
* Modifying the signal chain in any way (canvas also scrolls all the way back up - I assume this means it's being refreshed in some way)

The "asterisk" buttons on the left for disabled channels remain gray, but they have to be turned on and back off (while being careful not to double-click and enter single-channel view) for the channel to actually be disabled again. This is an annoying behavior that should be fixed.

**Comment by jsiegle** [comment]
This has now been fixed.
