### ISSUE TITLE
Timestamps produced by FileReader are inconsistent with other source processors

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/plugin-GUI#216]
The FileReader source seems to associate timestamps with each buffer corresponding to the total number of samples read _including_ the current buffer, in contrast with other sources which do _not_ include the current buffer. For example, when using the Rhythm FPGA, the very first buffer when starting acquisition has a timestamp of 0 (`getTimestamp(chan) == 0`), whereas when using the FileReader, the very first buffer has a timestamp equal to the number of samples in the buffer.

From FileReader::process:

```
    timestamp += samplesNeededPerBuffer;
    setTimestampAndSamples(timestamp, samplesNeededPerBuffer);
```

(where `timestamp` is initialized to 0 in the constructor).

I propose these two lines should be switched, to add the timestamp before it is incremented to include the current samples. Does that make sense?

**Comment by aacuevas** [comment]
yup, those two should be switched indeed. 
Thanks!
