### ISSUE TITLE
FileReader assumes an audio device with a sample rate of 44100 Hz

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/plugin-GUI#217]
In FileReader::process:

`const int samplesNeededPerBuffer = int (float (buffer.getNumSamples()) * (getDefaultSampleRate() / 44100.0f));`

This is the number of samples the node reads from the file on each callback. `samplesNeededPerBuffer` is calculated by converting the value of "Audio buffer size" in the Audio Settings window to seconds by dividing by 44100, and then to samples at the recording sample rate by multiplying by `buffer.getNumSamples()`. However, if the device sample rate is actually greater than 44100 (for example), the buffer size will correspond to a shorter time period, i.e. the callbacks will be more frequent than expected, but the same number of samples will be read on each callback, resulting in the data being read too fast.

The bug is reproducible by setting the audio device/sample rate to something greater than 44100 and observing that the LFP window "gets ahead" of the timer and the selected timebase. With a sample rate of 88200, for example, with the timebase set to 1 sec, each screen actually fills in 0.5 sec. (Incidentally, the default audio device on my machine is "Windows Audio" which has a sample rate of 48000 Hz, resulting in change in speed that is barely noticeable at first but gets the display out of sync with the timer before too long.)

If there's a way to read the actual device sample rate and use that instead of the constant, that seems like the easiest fix. Something like this would probably work:

```
AudioDeviceManager& adm = AccessClass::getAudioComponent()->deviceManager;
AudioDeviceSetup ads;
adm.getAudioDeviceSetup(ads);
double deviceSampleRate = ads.sampleRate;
```

(the tricky part might be monitoring changes to the sample rate so they trigger an update, actually.)

**Comment by aacuevas** [comment]
Hi,

Yes, that code did the trick. It is not necessary to track changes in sample rate, though, as it should never change during acquisition, so only an update once acquisition starts is needed.

Please double-check if it works as intended now.
