### ISSUE TITLE
Editor viewport displays editors in the wrong order (or they appear invisible) sometimes

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/plugin-GUI#233]
As shown below, sometimes the editor viewport will display editors in the wrong order. This happens when a long editor doesn't fit to the right of its source without going off the screen, but a later one in the chain does. Instead of leaving the rest of the space blank, the later editor gets displayed.

![editor_viewport_bug](https://user-images.githubusercontent.com/8973825/42114233-46277942-7bbc-11e8-8e31-c0ed4d02891d.png)

(I'm working on a fix to this which I will submit soon.)

**Comment by aacuevas** [comment]
This should be fixed with your pull request. Thank you!
