### ISSUE TITLE
The processor list is alphabetized by the plugin names rather than the display names

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/plugin-GUI#242]
(e.g. the "Spike Viewer" and "Spike Detector" are both alphabetized as if they were "BasicSpikeDisplay".)

Would be a little more intuitive if they were alphabetized by display names. Obviously this is a minor issue.

**Comment by jsiegle** [comment]
We're not going to worry about fixing this, since it only affects a small number of plugins.
