### ISSUE TITLE
settings.xml not saved in combination with impedance measurement

### ISSUE THREAD

**Issue by wonkoderverstaendige** [open-ephys/plugin-GUI#250]
I run v. 0.4.3.3 on Windows 10, and have several recordings where the settings.xml file was not stored. In those cases, the impedance measurements xml file is present. Perhaps when the directory exists already from the automatic impedance measurement, the settings file is not generated?

**Comment by jsiegle** [comment]
As of GUI version 0.6.0, the XML file containing impedance measurements is saved directly from the Acquisition Board plugin. So there shouldn't be any conflict between the settings XML and the impedance XML.
