### ISSUE TITLE
Get rid of sinks, change them to pass-through filters

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/plugin-GUI#256]
Just an idea for future enhancement: Why not make all the sinks into pass-through filters? Keep the functionality the same, except allow other processors to follow them in the chain and receive the same input as they do. This would eliminate the need for a lot of splitters - for example, if you want to monitor the signal at every point in the chain, currently you have to put a splitter and LFP viewer between each pair of processors, but if the LFP viewer passed its inputs through, you could just put viewers between each pair in a linear chain.

A downside would be breaking the nice symmetry of sources and sinks, but it seems like it would be purely an enhancement in terms of functionality.

**Comment by medengineer** [comment]
Added w/ PR #367
