### ISSUE TITLE
Update color scheme for Event Triggered Average display

### ISSUE THREAD

**Issue by jsiegle** [open-ephys/plugin-GUI#275]
Some of the channels are hard to see on a gray background.

**Comment by Claybarn** [comment]
Can fix this today. Will match LFP viewer color scheme to maintain a common aesthetic across plugins, unless someone object to this.

**Comment by vncntprvst** [comment]
That'd be great!
Thanks

**Comment by Claybarn** [comment]
Fixed in my latest push to the development branch. Just changed line 108 in EvntTrigAvgCanvas.cpp to:
`g.fillAll(Colour(0,18,43));`

making the background the same as in the LFP viewer. 

Let me know if this works! If not, can get into changing the color scheme.

**Comment by vncntprvst** [comment]
That's much better. Thanks!

**Comment by Claybarn** [comment]
Great! Thanks for the feedback. Will close this issue.
