### ISSUE TITLE
LFP Viewer does not draw events from sources without continuous data

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/plugin-GUI#284]
As stated in #277 the LFP viewer draws the TTLs in accordance with the sample counts of either the source processor (e.g. Rhythm node) or the source which samples are used to generate the TTLs (like in the Phase detector).

However, TTLs unrelated to any continuous signal are not drawn at all.

**Comment by jsiegle** [comment]
As of GUI version 0.6.0, sources must have at least one continuous channel. So this issue is no longer relevant.
