### ISSUE TITLE
Vertical artifacts in LFP Viewer

### ISSUE THREAD

**Issue by jvoigts** [open-ephys/plugin-GUI#29]
Every 10 (now 20) seconds, a 1-pixel vertical line appears in the LFP Viewer across all channels. Likely due to reaching the end of the 10-second display buffer.

not totally fixed but mostly usable now, in 0488eaa850f20c442a1360d81707fdd103ca92f7
there is still a small display issue if the end of the display
buffer is hit because now only 1-2samples are associated with the pixel
and this causes the min/max and histogram displays to look odd.
shouldn’t be a big issue in real applications but worth fixing when we
inevitably refactor this whole plugin.

this is due to reaching the end of the displaybuffer

**Comment by anjaldoshi** [comment]
Fixed in PR #348
