### ISSUE TITLE
improve subsampling of histogram data in lfpviewer

### ISSUE THREAD

**Issue by jvoigts** [open-ephys/plugin-GUI#30]
right now there's a hard limit on the N samples/px - instead we should do every 2nd sample etc for large numbers in order to sample more reliably and keep the cpu load down a bit.

**Comment by jsiegle** [comment]
The histogram-based visualization has been disabled as of GUI version 0.5.4 (although the code is still in there). Does anyone actually use this? I think it looks nicer in some cases, but not nice enough to justify the extra CPU load.

**Comment by jsiegle** [comment]
Closing this issue...I think the LFP Viewer generally looks pretty good, and subsampling is much more processor intensive than just using min/max for each pixel.
