### ISSUE TITLE
OS freezes if moving/resizing window while a popup appears [Win]

### ISSUE THREAD

**Issue by medengineer** [open-ephys/plugin-GUI#306]
Reproducible: Win10

Happened while resizing GUI when Neuropixels probes were loading and calibration notification popup appeared. Cursor gets stuck in the resize (double-arrow) configuration and freezes the entire OS. Ctr+Alt+Del regains control, do not need to exit GUI. 

Likely an issue secondary to improper display mutex handling...

**Comment by jsiegle** [comment]
This should be fixed now, but please re-open this issue if you notice it again.
