### ISSUE TITLE
Gui can be closed without warning

### ISSUE THREAD

**Issue by greggheller** [open-ephys/plugin-GUI#313]
Accidentally clicking the close X promptly closes the gui even during recording. Was thinking there should probably be a warning box to confirm that closing the gui is desired.

**Comment by aacuevas** [comment]
That could be a nice addition, and easy to do.

I wonder if the GUI should just always ask, or only when acquiring. Also, if that same dialog should trigger when closing the GUI via other means (for example, when shutting down Windows)

**Comment by jsiegle** [comment]
This feature has been added in the latest version of the GUI
