### ISSUE TITLE
Computer  specifications

### ISSUE THREAD

**Issue by sandraromerop** [open-ephys/plugin-GUI#315]
Hi all,

First of all, Thanks a lot in advance for all the effort put in this project,

I'm trying to get settled with open ephys and would like some advice on the computer hardware and system requirements for performing recordings from >=128  simultaneous channels , with potential online PSTH computation and sorting . 

Are there any minimal requirements in the RAM size, drive size , processor (in windows)  for preventing crashes while recording?

thanks a lot! 
sandra

**Comment by jsiegle** [comment]
Recommended computer specs are now documented here: https://open-ephys.github.io/gui-docs/User-Manual/Hardware-requirements.html
