### ISSUE TITLE
Recording via RHD2164 and Intan acquisition board results in digital glitches

### ISSUE THREAD

**Issue by DoktorDu** [open-ephys/plugin-GUI#318]
When recording using RHD2164 with Intan acquisition board, channels 1-32 look fine but channels 33-64 have digital glitches. When viewed via RHD2000 Evaluation System software + Neuroscope all channels look fine.

The headstage appears correctly as one 64ch in Rhythm FPGA. Is this a known bug?

**Comment by jsiegle** [comment]
The RHD2164 chips should be fully supported, and we've done many recordings without apparent glitches.

If you're still experiencing this problem with the latest version of the GUI, please open an issue in the Rhythm Plugins repository: https://github.com/open-ephys-plugins/rhythm-plugins
