### ISSUE TITLE
Weird artifact/peak/spike every ~10s; on vers.>0.4.4.1; NOT on v.0.4.2.1

### ISSUE THREAD

**Issue by cskoven** [open-ephys/plugin-GUI#322]
I recently pulled the newest source from this repo, and compiled it.
However I get a weird "artifact/peak/spike/something" on what appears to be all my ADC-channels - every 10s.

![Screenshot from 2019-10-07 16-13-51](https://user-images.githubusercontent.com/22638608/66319577-9edb3400-e91d-11e9-9a17-942b95668fc2.png)

I've tried to use the latest released binary file, which give the same weird artifact.
My old version (compliled from source; v.0.4.2.1) does not give this weird artifact.

I've tried to setup the "pipeline"/signal chain completely similar - with/without using saved config files. But the problem seems to lie with the version of the software, rather than the signal chain config.

When compiling, I get a lot of lines (not errors per se) about "class LookAndFeel" (forward declaration), but it finishes the compilation and the program runs fine. I don't know if this has anything to do with it? I guess it shouldn't, as it's also a problem with the binary v.0.4.4.1-file.

It's running on a machine with: Ubuntu 18.04.2 LTS

Does anyone have any insight?

**Comment by anjaldoshi** [comment]
Hi,

Thanks for providing a detailed analysis on the issue. We're aware of this "artifact", and it is a part of my TODO list.

I had one detail that I wanted to confirm with you. Did you get a chance to look at the recorded data and see whether this artifact shows up in it?

**Comment by anjaldoshi** [comment]
Fixed in PR #348
