### ISSUE TITLE
Adding custom plugin

### ISSUE THREAD

**Issue by holmescharles** [open-ephys/plugin-GUI#327]
A labmate wrote a custom plugin for my setup a long time ago. I just updated open-ephys, but the build structure is much different. I used to be able to just copy the ".so" file of the custom plugin into the plugins directory, but that does not seem to work.

If I have a built ".so" file, where can I put this so open-ephys "loads" it? (I am working on Ubuntu if that helps). Thanks!

**Comment by aacuevas** [comment]
The location for plugins is still the same, as the way to load them. However, in last version there were some changes to the plugin API that requires plugins to be built again against it. We try to avoid making such changes as much as possible, but sometimes they are unfortunately required. It is probable your plugin was built for the previous API version and needs to be rebuilt.

Looking at the console when starting the GUI should confirm you if that is indeed the case or nor, as the plugin should be listed but showing an error message.

**Comment by holmescharles** [comment]
It didn't show, but I have downgraded to an older version of the plugin GUI for now.

On Wed, Oct 30, 2019 at 5:51 PM Aarón Cuevas López <notifications@github.com<mailto:notifications@github.com>> wrote:

The location for plugins is still the same, as the way to load them. However, in last version there were some changes to the plugin API that requires plugins to be built again against it. We try to avoid making such changes as much as possible, but sometimes they are unfortunately required. It is probable your plugin was built for the previous API version and needs to be rebuilt.

Looking at the console when starting the GUI should confirm you if that is indeed the case or nor, as the plugin should be listed but showing an error message.
