### ISSUE TITLE
binaries for mac os 10.13 high sierra

### ISSUE THREAD

**Issue by robinmeier** [open-ephys/plugin-GUI#351]
can't find download links for older binaries. is there a server/repository somewhere that i missed?

thanks

**Comment by robinmeier** [comment]
the latest binary works only for mac os 10.15 and upwards

**Comment by medengineer** [comment]
You can find the older binaries [here](https://github.com/open-ephys-GUI-binaries/open-ephys/tree/mac).

**Comment by robinmeier** [comment]
awesome. thanks
