### ISSUE TITLE
export audio as wav file 

### ISSUE THREAD

**Issue by robinmeier** [open-ephys/plugin-GUI#353]
is there a way to export channels as wav files rather than listening to them in realtime through the audio monitor?

**Comment by aacuevas** [comment]
Neither the GUI nor our tools have such functionality. 
You could easily do it with MATLAB, though. Just load the data, isolate the channel you want to save into its own vector and use the `audiowrite` MATLAB function.

An example code could be:
```{MATLAB}
D=load_open_ephys_binary('structure.oebin','continuous',1);
CH2=D.Data(2,:);
CH2Norm=CH2/(max(abs(CH2))); %when using a double vector, audiowrite needs the data to be in the range -1 - +1
audiowrite('channel2.wav',CH2Norm,D.Header.sample_rate);
```
