### ISSUE TITLE
juce::Point

### ISSUE THREAD

**Issue by Claybarn** [open-ephys/plugin-GUI#355]
Have to change all instances of `Point` to `juce::Point` on Xcode 11.5

**Comment by anjaldoshi** [comment]
We added a commit for the same on master a couple of weeks ago, and we are adding that to development too. 
This problem was introduced in one of the macOS Catalina updates which is making JUCE's Point class ambiguous.

**Comment by anjaldoshi** [comment]
Fixed in 64d77e7b403876b1337514404d9052fa8a820d07
