### ISSUE TITLE
windows build 0.4.6 needs FrontPanelUSB-driver 

### ISSUE THREAD

**Issue by stowerslab** [open-ephys/plugin-GUI#356]
hi I think the newest downloadable  windows build of open ephys 0.4.6 needs the frontpanelusb-driver only-4.5.5.exe to be installed. this was bundled with the previous version 0.4.5 but was missing in the latest version

**Comment by jsiegle** [comment]
@medengineer, can you look into this?

**Comment by medengineer** [comment]
[0.4.6 Windows binary](https://dl.bintray.com/open-ephys-gui/Release/ ) has been updated to include the driver.
