### ISSUE TITLE
Build procedure for plugin cannot find headers

### ISSUE THREAD

**Issue by FelixAntonSchneider** [open-ephys/plugin-GUI#358]
Hi,
I wanted to test building and installing plugins from source with the neuropixels-pxi plugin. Generating the build files with cmake seems to work flawlessly. However when I try to build the project then in Visual Studio 16 2019, the procedure fails, because it cannot find certain header files, which are in the plugin-GUI repo.
I'm aware that the repos of the plugin-GUI and the plugin itself should be side by side in the same folder, but the problem still persists

C:\Users\Admin\source\open_ephys\GUI
C:\Users\Admin\source\open_ephys\Neuropixels-pxi

I also tried setting the path to the GUI repo together with the cmake command as mentioned on the wiki, but that doesn't help either.

This is the console output from Visual Studio 16

1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
1>CMake is re-running because generate.stamp.list is missing.
1>-- Building for: Visual Studio 16 2019
1>-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
1>-- The C compiler identification is MSVC 19.26.28806.0
1>-- The CXX compiler identification is MSVC 19.26.28806.0
1>-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
1>-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
1>-- Detecting C compiler ABI info
1>-- Detecting C compiler ABI info - done
1>-- Detecting C compile features
1>-- Detecting C compile features - done
1>-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
1>-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
1>-- Detecting CXX compiler ABI info
1>-- Detecting CXX compiler ABI info - done
1>-- Detecting CXX compile features
1>-- Detecting CXX compile features - done
1>-- Configuring done
1>-- Generating done
1>-- Build files have been written to: C:/Users/Admin/source/open_ephys/neuropixels-pxi/Build
2>------ Build started: Project: neuropixels-pxi, Configuration: Debug x64 ------
2>Building Custom Rule C:/Users/Admin/source/open_ephys/neuropixels-pxi/CMakeLists.txt
2>NeuropixComponents.cpp
2>C:\Users\Admin\source\open_ephys\neuropixels-pxi\Source\NeuropixComponents.h(27,10): fatal error C1083: Cannot open include file: 'DataThreadHeaders.h': No such file or directory
2>NeuropixEditor.cpp
2>C:\Users\Admin\source\open_ephys\neuropixels-pxi\Source\NeuropixThread.h(28,10): fatal error C1083: Cannot open include file: 'DataThreadHeaders.h': No such file or directory
2>NeuropixThread.cpp
2>C:\Users\Admin\source\open_ephys\neuropixels-pxi\Source\NeuropixThread.h(28,10): fatal error C1083: Cannot open include file: 'DataThreadHeaders.h': No such file or directory
2>OpenEphysLib.cpp
2>C:\Users\Admin\source\open_ephys\neuropixels-pxi\Source\OpenEphysLib.cpp(24,10): fatal error C1083: Cannot open include file: 'PluginInfo.h': No such file or directory
2>Generating Code...
2>Done building project "neuropixels-pxi.vcxproj" -- FAILED.
3>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
3>Building Custom Rule C:/Users/Admin/source/open_ephys/neuropixels-pxi/CMakeLists.txt

I would much appreciate your help. I haven't worked with C++ or Visual Studio before

Cheers,
Felix

**Comment by anjaldoshi** [comment]
Hey Felix,

Couple of things to note here. First, the wiki says the plugin repo needs to be cloned at the same level as plugin-GUI, which is what you did. But, in reality, the plugin needs to be _inside_ a directory (e.g. OEPlugins) that is at the same level as plugin-GUI. So, in your case, it should be:

C:\Users\Admin\source\open_ephys\GUI
C:\Users\Admin\source\open_ephys\ _[OEPlugins]_ \Neuropixels-pxi

I've updated the [wiki](https://open-ephys.atlassian.net/l/c/VL3XM2oU) to reflect the same. 
If you don't want to change your directory structure then you can simply set the path to the GUI via cmake as you did already. 

Second, the reason you're facing these errors is because you are building the ZERO_CHECK project for that plugin (which might be the default selected project). If you look at the [wiki](https://open-ephys.atlassian.net/l/c/VL3XM2oU), it says you have to build the ALL_BUILD project. That will run the build process on all projects except INSTALL, thus building the plugin. Selecting the INSTALL project and building it will trigger the install procedure, copying the plugin and any required files, if any, to the GUI's appropriate directories. 

Also, before building any project, make sure the build config is set to Release and x64 (see image below) if you just want to build and use the plugin. If you want to debug the plugin using VSDebugger, then select Debug and x64. 
![75574791-c6898080-5a13-11ea-9e3d-7e173fb3d74a](https://user-images.githubusercontent.com/11559287/84441862-651ba500-abf1-11ea-884e-ab54c21e6ff7.png)

Let me know if you have any further concerns.

**Comment by FelixAntonSchneider** [comment]
Thanks for your response.

Regarding the folder structure. "plugin-GUI" refers to the top level folder containing the entire standard repo or are you talking about the plugin-GUI folder within the standard repo, which sits right next to the Plugins folder?

So is it 
C:\Users\Admin\source\open_ephys\**plugin-GUI**\plugin-GUI
C:\Users\Admin\source\open_ephys\plugin-GUI\OEPlugins

or 

C:\Users\Admin\source\open_ephys\**plugin-GUI**
C:\Users\Admin\source\open_ephys\OEPlugins

where the bold plugin-GUI refers to the repo

Either way I run into the same issue. I'm not sure whether I do something wrong within Visual Studio. I either go to and click Build/Build ALL_BUILD or select ALL_BUILD in the solution explorer, right-click and click Build. Shouldn't that work? I also built and installed the plugin-GUI from source again, this time as Release, and subsequently tried to build the plugin as Release as well. Also didn't change anything.

I also think the reason why the first print message refers to ZERO_CHECK is because ZERO_CHECK is at the top of the Build order of the ALL_BUILD project. 

![plugin_build_order](https://user-images.githubusercontent.com/42135900/84671113-4128ce00-af27-11ea-9285-300f268c814b.png)

So I don't think this is a mistake. Also the ZERO_CHECK part seems to work. The problems start during the neuropixels-pxi project, because it can't find those header files, as I mentioned above.
But maybe the ZERO_CHECK is not supposed to be there in general?
Maybe you can spot something suspicious in my solution explorer?

![solutions_explorer](https://user-images.githubusercontent.com/42135900/84672581-fe67f580-af28-11ea-8ddb-b2a3c9a4f648.png)


I also tried running "Build only ALL_BUILD", but that doesn't get me anywhere either.

**Comment by FelixAntonSchneider** [comment]
The build and install procedure now ran through after setting the environment variable GUI_BASE_DIR and building as Release. No errors in VS16 anymore.
However the .dll file, which was exported to the Build/Release/plugins folder seems corrupted. It is not loaded during startup of the plugin-GUI.

![plugin_dll_load_failure](https://user-images.githubusercontent.com/42135900/84677163-a16f3e00-af2e-11ea-95f6-ad6cb5a5784b.png)

**Comment by FelixAntonSchneider** [comment]
Just built and installed the StreamMuxer-plugin from source the same way as above. Worked fine and the plugin is recognized and loaded upon start-up of

**Comment by medengineer** [comment]
The Neuropixels-PXI module requires additional .dlls to communicate with the hardware. Copy over the .dlls found in the Neuropixels-PXI/Resources folder to the plugin-GUI/Build/Release/shared directory.

**Comment by FelixAntonSchneider** [comment]
Ah ok. Thanks a lot for the info! Now it is recognized and loaded.
Could the build/install procedure be changed, so that it also copies over those files. Because it does so with the plugin.dll file right?
