### ISSUE TITLE
Build Issue`

### ISSUE THREAD

**Issue by macayladonegan** [open-ephys/plugin-GUI#359]
after using:
cmake -G "Visual Studio 12 2013" in the  \Documents\GitHub\plugin-GUI\Builds\VisualStudio2013 folder

I keep getting this error:
CMake Error: The source directory "C:/Users/Macayla/Documents/GitHub/plugin-GUI/Builds/VisualStudio2012" does not appear to contain CMakeLists.txt.

any advice?

**Comment by medengineer** [comment]
After cloning the plugin-GUI, you should have an empty Build directory. Open a terminal in the Build directory and use the command 

`cmake -G "Visual Studio 12 2013 Win64" ..` 

This tells cmake to generate the build files for Visual Studio 12 in the Build directory using the CMakeLists.txt in the parent (..) directory.

**Comment by macayladonegan** [comment]
hmm ok I don't have the empty build directory, any idea what to do about that?

**Comment by medengineer** [comment]
Looks like you’re using a much older version of the plugin-GUI since you have the old Builds directory. I would either do a ‘git pull’ to get the most recent changes or clone a fresh copy.
