### ISSUE TITLE
Crash on writing open ephys format with no events

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/plugin-GUI#391]
The open ephys format crashes when trying to record a chain with no event channels.

Tested by a simple File Reader -> Record Node -> LFP Viewer, with Open Ephys format selected.

Crash happens on  OriginalRecording::openFile (OriginalRecording.cpp:126) but the actual culprit comes from OriginalRecording::openFiles (OriginalRecording.cpp:94) as to open the events file it uses the first event channel as parameter to detect the file type.

Older versions did not have this issue because the message center was always connected to the record node, so there were always at least one event channel.

**Comment by jsiegle** [comment]
Ok, that makes sense. In our testing we always had at least one additional event channel in there.

We already have a fix for this, which we'll include in the next release (hopefully coming next week).
