### ISSUE TITLE
Display NI-DAQ events in LFP viewer

### ISSUE THREAD

**Issue by lachioma** [open-ephys/plugin-GUI#394]
Is it possible to have one LFP viewer that displays ephys data from Neuropix-PXI overlaid with events coming from NI-DAQmx?

If not possible, being able to view data from multiple sources (e.g. Neuropix-PXI and NI-DAQmx) would be a very useful feature to have.

Thank you!
Alessandro

**Comment by jsiegle** [comment]
It's not possible to overlay the events directly, but you can use two separate LFP Viewers to visualize the NIDAQ events on the same timebase as the Neuropixels data. Just pop out one of the LFP Viewers into its own window, which you can place directly above or below the other one. Let me know if that works!

**Comment by lachioma** [comment]
Thank you, it works (see screenshot). 
You just need to use "pause" on one of the two LFP viewers to align the vertical line cursor. Also, the cursors do not move at exactly the same speed (i.e. the clocks are different), so they have to be re-aligned every few minutes.

![openephys LFP](https://user-images.githubusercontent.com/29898879/103106414-559b0100-4603-11eb-86f1-068ca2368047.png)

**Comment by jsiegle** [comment]
This functionality is much improved with the latest version of the LFP Viewer. You can now split the display horizontally, so the Neuropixels and NIDAQ channels are stacked on top of one another. There is also a "sync displays" button that resets all displays to the left side of the screen.

More information can be found here: https://open-ephys.github.io/gui-docs/User-Manual/Plugins/LFP-Viewer.html
