### ISSUE TITLE
Record Node not recording all channels

### ISSUE THREAD

**Issue by PhilNeuro** [open-ephys/plugin-GUI#397]
A very strange issue (Windows 10, OE v0.5.2.2).  We use 3 FPGA modules.  The 3rd one has 128 channels connected, and they are shown correctly on the interface. These signals can be seen on a viewer later in the processing chain.  However, only 8 channels are recorded.  The record-node's 'settings.xml' file indicates that we do have 128 channels, but the associated structure.oebin only lists 8 channels, which is what we can find in the continuous.dat file.    On this setup, we have a total of 512 channels.   Is it possible that we have to fill the FPGAs  in sequence before adding channels to the next board ?
![test](https://user-images.githubusercontent.com/43388086/102524067-7218c580-4066-11eb-9c7f-56d3a28efc93.png)

**Comment by jsiegle** [comment]
That is indeed strange. Can you attach the settings.xml file to this issue? Also, can you try deselecting all of the channels in Rec 109 "SP0" interface, then re-selecting them and see if that fixes the problem?

Also, I'm interested to know what the Spike Monitor plugin does!

**Comment by PhilNeuro** [comment]
Here is the 'settings.xml' file, thanks!   I just saw that the record node lists all 128 channels, but only marks 8 of them with a recordstate of '1'.   I deselected and reselected them in both the FPGA and REC 109 modules without change.
[settings.zip](https://github.com/open-ephys/plugin-GUI/files/5711346/settings.zip)

The spike monitor is my merged version of Spike Detector and Viewer where only a subset of the acquired channels are active and visible at once, needed for our high count channel system where we only store continuous data anyway.   Functional but not yet fully debugged.  
![test2](https://user-images.githubusercontent.com/43388086/102527076-9e364580-406a-11eb-96b6-ae145f6bf52d.png)

**Comment by jsiegle** [comment]
Thanks! At least the settings file is consistent with the actual behavior. 

Are you using the Record Node selection interface to toggle the channels on/off, as in the attached image? The "PARAM" buttons don't have any effect in the new Record Node.

<img width="478" alt="Screen Shot 2020-12-17 at 10 28 18 AM" src="https://user-images.githubusercontent.com/200366/102527879-a3879600-4052-11eb-8937-361ad1348196.png">

**Comment by PhilNeuro** [comment]
Bingo !  I was using the PARAM button  !    I used to collect only 8 channels on this FPGA, and just added 128 without modifying the signal chain.   I assumed the 'updateSettings' calls would take of this since the PARAM section was correctly updated.   Is it possible that adding/removing signals on my FPGA does not automatically change the record-node  active inputs ?

**Comment by jsiegle** [comment]
This is something we'll need to look into. The default behavior should be to record all additional channels if the number of inputs to the Record Node increases. If that's not the case right now, then we'll get that fixed.

**Comment by PhilNeuro** [comment]
All right, thanks a lot, this was very helpful (and fast !)
