### ISSUE TITLE
drop down box for file save path does not correspond to default save path

### ISSUE THREAD

**Issue by olliopti** [open-ephys/plugin-GUI#399]
Problem: Default save path always C:\users\<currentuser>\documents as opposed to the path name seen in the GUI on startup.

Details: The default path in the drop down save box at the top of the plugin-GUI and the record node doesn't correspond to where the record node saves by default. The record nodes disc full indicator corresponds to the C: drive by default even if the path in the record node appears to be the D: drive. Only when we explicitly re-selected the path in the record node were we able to save the data in the expected location. 

System: Windows 10 professional, OEP version 0.5.2

**Comment by jsiegle** [comment]
This should be fixed in the latest version...can you try upgrading to 0.5.3?
