### ISSUE TITLE
version 0.5.3 impedance measure not working  

### ISSUE THREAD

**Issue by dlayfiel** [open-ephys/plugin-GUI#407]
Is anyone else having issues using the impedance measure function on the 0.5.3 version of the open ephys software, im use to the gui just not look likes its doing anything like in the previous versions but the software is literally doing nothing when I click the measure the impedance button.

**Comment by jsiegle** [comment]
I'm not able to reproduce this (tested on Windows with v0.5.3). Can you provide some more details about your setup? For example, what type of headstages are you using?

**Comment by sppmg** [comment]
Hi,
I got same issue in version v0.5.5.3 and v0.5.5.2.
The debug console display `Saving impedance  measurements in \impedance_measurements.xml`
![擷取](https://user-images.githubusercontent.com/6098465/140700076-6f30458a-b58f-4a65-a444-d24ed35b75d0.PNG)

And I tried output format in  `Open ephys` and `NWB`, same result.

**Comment by jsiegle** [comment]
I believe the saving of impedance measurements was likely broken when we switched over to the Record Node system in v0.5.0+. This will be restored in the next major release (v0.6.0), but for now you'll just have to screenshot the Rhythm FPGA configuration window.

If someone has been successfully saving impedance measurements in recent version of the GUI, please let me know!

**Comment by sppmg** [comment]
Oh...
The `screenshot` is too inefficient (we need log it to spreadsheet). Instead, I will use `v0.4.6` to save impedance file, it's work on same system.

Thanks your reply and hope new version coming soon.

**Comment by jsiegle** [comment]
Impedance measurements can now be saved directly from the Acquisition Board plugin. For more information, see the [Rhythm Plugins](https://open-ephys.github.io/gui-docs/User-Manual/Plugins/Rhythm-Plugins.html) documentation page.
