### ISSUE TITLE
GUI crashes when loading settings with Rhythm FPGA plugin

### ISSUE THREAD

**Issue by ldclaar** [open-ephys/plugin-GUI#413]
Hello,

I am using Open Ephys, version 0.5.3, with Windows 10. I have noticed that the GUI crashes if I try to open a saved settings file that contains the Rhythm FPGA source plugin. This happens even though the Open Ephys acquisition board and headstage are connected (and recognized if I add the plugin manually).
![OpenEphys_v0 5 3_fails to load settings with FPGA](https://user-images.githubusercontent.com/45570217/107307783-3550c580-6a3c-11eb-92fb-3e693a13afa8.JPG)

It also crashes if I try to reopen the GUI if the Rhythm FPGA plugin was in use prior to closing the GUI. It continues to crash until I delete the lastConfig.xml file. After deleting that file, the GUI opens successfully.
![OpenEphys_v0 5 3_fails to load last config with FPGA](https://user-images.githubusercontent.com/45570217/107307833-574a4800-6a3c-11eb-8d8d-918d4d15f34f.JPG)

I don't have the problem with the Neuropixels PXI plugin though, which is the only other plugin I have been using.

Thanks,
Leslie

**Comment by jsiegle** [comment]
Hi Leslie,

This is fixed in the latest release—if you upgrade to [v0.5.3.1](https://github.com/open-ephys/plugin-GUI/releases/tag/v0.5.3.1) the config files should load again.

**Comment by ldclaar** [comment]
Indeed, they do! Thanks!
