### ISSUE TITLE
Spike Viewer Visualizations - Signal Chain Tutorial

### ISSUE THREAD

**Issue by cgaletzka** [open-ephys/plugin-GUI#416]
I experience some troubles with the spike viewer module in the most recent release. I followed the tutorial for building a signal chain on a MacBook as described here: https://open-ephys.github.io/gui-docs/User-Manual/index.html

There is something wrong with the visualizations shown in the viewport: 
<img width="1277" alt="Screen Shot 2021-02-23 at 9 23 50" src="https://user-images.githubusercontent.com/57383165/108789197-18300100-75bd-11eb-85bc-60039a250b25.png">

I also did the the tutorial with the older GUI on a windows PC. Here, the visualizations look fine: 
![Untitled](https://user-images.githubusercontent.com/57383165/108789527-ccca2280-75bd-11eb-9e73-3f1548c61ef7.jpg)

I'm not sure if this difference is caused by a setting in the GUI or due to the hardware. The signals look fine when viewed in the LFP Viewer. Help would be greatly appreciated!

**Comment by jsiegle** [comment]
Hmm...I'm not seeing this on my iMac or Mac laptop. What version of macOS are you using? Any chance you have an M1 chip?

**Comment by cgaletzka** [comment]
Sorry I haven't mentioned the specs. I'm using macOC 11.0.1 Big Sur on a 2.3 GHz Dual-Core Intel i5 with 16 GB RAM. The issue also persists after reinstalling the GUI.

**Comment by jsiegle** [comment]
Ok, looks like this is a known issue with Big Sur: https://forum.juce.com/t/apparent-serious-juce-painting-issue-in-big-sur/43430/33

Our next big project (~3 month timescale) is to upgrade to the latest version of JUCE, which should solve the problem (at least according to the linked thread). Unfortunately, I don't think we'll be able to fix it before then.

**Comment by cgaletzka** [comment]
Okay, thank you for your help!

**Comment by jsiegle** [comment]
How does the LFP Viewer look? Is that usable?

**Comment by cgaletzka** [comment]
Yes, the LFP Viewer works fine.

**Comment by jsiegle** [comment]
The GUI now uses version 6 of the JUCE library, which solves this problem.
