### ISSUE TITLE
Issues with Apple Arm64?

### ISSUE THREAD

**Issue by lstrgar** [open-ephys/plugin-GUI#420]
Hi. Wondering if anyone has observed success/failure with the GUI on Apple's new M1 chips? Thanks for any info you can share. 

Luke

**Comment by ANickerson** [comment]
I have not been able to build it, but the prebuilt images seem to work.

**Comment by ANickerson** [comment]
it appears adding `set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE STRING "Build architecture for Mac OS X" FORCE)` to the cmake config enabled the build
