### ISSUE TITLE
noise seems to increase with reference 

### ISSUE THREAD

**Issue by Grand-Laborer** [open-ephys/plugin-GUI#424]
We are recording signals on a treadmill with a tetrod in a mouse.

Without reference, the LFP only has a little noise, but the noise greaty increase when the treadmill is on.

With reference, the LFP seems more noisy than that without reference when the treadmill is off. And noise is affected less when the treadmill is on.

Should noise increase with reference? Is there anyway to lower the affect of treadmill?

Thanks.
![no reference, treadmill off](https://user-images.githubusercontent.com/66052703/112837848-f7346180-90ce-11eb-963a-107343543898.PNG)
![reference, treadmill off](https://user-images.githubusercontent.com/66052703/112837868-fdc2d900-90ce-11eb-8a78-a41d5bec1eb8.JPG)

**Comment by jsiegle** [comment]
Hi @Grand-Laborer – I'm closing this issue for now, but feel free to re-open if you're still experiencing this problem, and we can help you troubleshoot.
