### ISSUE TITLE
Renaming TTL Event actually renames Channel?

### ISSUE THREAD

**Issue by dstolz** [open-ephys/plugin-GUI#425]
Hello,

I have found what seems to be a bug in naming TTL lines in Open Ephys GUI (v 5.3.1).  When I enter a name for a TTL line, it updates the channel name with the same number (see example screen captures below).  This happens for all TTL lines 1-8. 

Any suggestions how to fix this?

Thank you,
Daniel

![image](https://user-images.githubusercontent.com/11509429/113164285-f99dd500-920e-11eb-933d-63fc1461e59e.png)
![image](https://user-images.githubusercontent.com/11509429/113164387-0d493b80-920f-11eb-893a-3d58071d0194.png)
![image](https://user-images.githubusercontent.com/11509429/113164440-1afec100-920f-11eb-9294-ba38a32e8534.png)

**Comment by jsiegle** [comment]
Thanks for pointing that out! This is fixed in pull request #426 , which we'll merge before the next release (likely sometime in mid-April).
