### ISSUE TITLE
"Unwanted" ADC streams get recorded

### ISSUE THREAD

**Issue by biomath** [open-ephys/plugin-GUI#438]
Hi,
Intan Recording Controller + v0.5.4 + Windows 10 here.
Even though I'm selecting only one ADC stream in my Record Node, all streams get saved in Open Ephys data format. Channels 1-64 are data channels; Channels 65-67 are non-connected; Channels 68-75 are ADC. Screenshots attached.
Thanks!

![image](https://user-images.githubusercontent.com/7768262/115924061-33987a80-a44d-11eb-9aba-3ad2b5ea21e3.png)

![image](https://user-images.githubusercontent.com/7768262/115924126-4f9c1c00-a44d-11eb-96d7-192ba5be6119.png)

**Comment by jsiegle** [comment]
This bug is fixed in this branch: https://github.com/jsiegle/plugin-GUI/tree/0.5.4-pre-release

@medengineer, can you double check that everything looks ok? I just made sure the ADC channels are added to the `dataChannelOrder` map, because previously they were being ignored.

**Comment by jsiegle** [comment]
We will make sure these changes get merged before the next release later this week!

**Comment by jsiegle** [comment]
This is fixed in the latest release.
