### ISSUE TITLE
Spike Viewer time window is off-center

### ISSUE THREAD

**Issue by Barryjuait** [open-ephys/plugin-GUI#454]
Hi,
It looks like the time window of the detected spikes are totally off toward the right, so I miss the whole depolarization period. Im using GUI v.0.5.4 

![image](https://user-images.githubusercontent.com/12356239/120461459-50a06180-c39a-11eb-80e7-e19e46346060.png)

**Comment by Barryjuait** [comment]
Update: the problem is solved if I use Spike sorter in the pipeline instead of Spike detector before the spike viewer.

![image](https://user-images.githubusercontent.com/12356239/120462021-d3292100-c39a-11eb-9954-347064d8ee0a.png)

**Comment by jsiegle** [comment]
Yeah, the spike polarity conventions on the Spike Detector need to be updated; please use the Spike Sorter for now.

**Comment by jsiegle** [comment]
This issue has been fixed in the Spike Detector for a while now. Also, in the latest version of the GUI, only the Spike Detector can detect spikes (the Spike Sorter just adds a `sortedID` label).
