### ISSUE TITLE
Synching a 5V pulse with Neuropixels data stream

### ISSUE THREAD

**Issue by Darkweiss** [open-ephys/plugin-GUI#455]
We have a function generator sending a 5V pulse to a NI PXIe-6341 through a BNC. The pulse shows up on the NIDAQMX data source (picture). We are also able to detect the rising and falling edge events with crossing detector. However, so far we have been unable to synchronise these TTL events with the data from a single Neuropixels probe in order to plot PSTH plots. The PSTH plots below were made with spike times from Kilosort2  and the events timestamps were calculated as TTL event minus the time of the first time sample of NIDAQMX. However, the first time sample of NIDAQMX is not the same as the Neuropixels one. What is the easiest way to synchronise these 2 data streams?
![image](https://user-images.githubusercontent.com/40541973/120824191-1aa4de00-c550-11eb-9ad8-63672633877c.png)
![image](https://user-images.githubusercontent.com/40541973/120824431-5dff4c80-c550-11eb-82bc-0419404213f1.png)

**Comment by medengineer** [comment]
You are very close! In order to synchronize, the 5V pulse needs to feed into a _digital_ input of the NI card, whereas in your example here, the right LFPViewer shows the 5V pulse is feeding into the first _analog_ input of the card.

**Comment by Darkweiss** [comment]
That now works. Thank you @medengineer! However, when looking at the event times of the crossing detector plugin, they do not seem to be aligned with the pulse. I guess we can do thresholding from the analogue signal but it would be nice if we already have the event times from Open Ephys.
![image](https://user-images.githubusercontent.com/40541973/121019095-07d01a80-c797-11eb-8c6d-15410102acdf.png)

**Comment by medengineer** [comment]
The CrossingDetector events are not exactly aligned with the Neuropixels events in the LFPViewer because synchronization only occurs in the RecordNode and the synchronized data only propagates to the recorded files (and not downstream processors). In the recorded data, the CrossingDetector event timestamps will each map to a synchronized source processor timestamp (in seconds) and the events should be aligned as expected.
