### ISSUE TITLE
Timestamps relative to onset of recording

### ISSUE THREAD

**Issue by lstrgar** [open-ephys/plugin-GUI#456]
Hi. I understand when recording continuous data a timestamps.npy file is generated effectively indexing samples relative to the onset of acquisition. Is it possible to determine the precise onset of acquisition or the precise onset on recording as a unix timestamp, for example?

**Comment by medengineer** [comment]
Hi, it is possible to add a line of code to achieve this if you're building the GUI from source. If using the Binary Format, for example, you can fetch the unix timestamp and append it to the sync file [here](https://github.com/open-ephys/plugin-GUI/blob/master/Source/Processors/RecordNode/BinaryFormat/BinaryRecording.cpp#L679).
