### ISSUE TITLE
Error in timestamps for buffers with more than 1024 points

### ISSUE THREAD

**Issue by bmsousa91** [open-ephys/plugin-GUI#457]
I'm using the Open Ephys, together with Pulse Pal, to record channels from an Intan RHD 2132 headstage and to trigger closed-loop stimulation. The GUI version is v0.5.4. I noticed some jitters on timestamp data when testing different buffer sizes. Only buffers with more than 1024 points present this issue and it gets progressively worse as the buffer size increases. I'm using "load_open_ephys_data_faster.m" to load the data and the info.ts variable is not correctly spaced by 1024.

For the figure attached I recorded only the first channel using the following process chain: Rhythm FPGA (30 kHz) -> Bandpass Filter -> Record Node -> LFP Viewer. I'm aware of the announcement made about timestamp issues (https://github.com/open-ephys/data_fix_0.4.2) and I tested the following actions, with no success: i) marked the "use separate files" recording option; ii) clicked first on the recording button, as opposed to clicking first in the play button and then record; iii) recorded more than 1 channel (channels 1, 2 and 3).

One workaround would be to create my own timestamps based on the sampling rate, but the timestamps of events still would have to be adjusted. For example, an event with the timestamp of 35 seconds could have happened at the real 35 seconds of recording or during the "high state of a square wave" in the figure, which reaches the same timestamp value. Would you know if there is something wrong with my settings? Thanks in advance!

![Ts error for buffer sizes bigger than 1024](https://user-images.githubusercontent.com/35617322/121908203-25573400-cd03-11eb-8bb9-e278416cc5c0.PNG)

**Comment by medengineer** [comment]
Thanks for reporting this, your settings are correct. We are able to replicate this issue on our end and are working on a fix.

**Comment by jsiegle** [comment]
We figured out the source of this problem (the Record Node `DataQueue` was getting overrun if more than 1024 samples arrived in a single buffer). It's fixed in pull request #460, which we'll merge before the next release.

**Comment by bmsousa91** [comment]
Great! Thank you for the support.
