### ISSUE TITLE
RHD2132 headstage not detected by the GUI (Windows)

### ISSUE THREAD

**Issue by chiyu1203** [open-ephys/plugin-GUI#462]
Hi my question is quite simliar to #219 but I used Windows 10 so I thought I made another question here.
I have been using RHD2132 headstage with openEphys board v2.2 to do recording (GUI version 0.4.5) for the past two years. It was fine at least until my last recording in this Feb 2021.
This week, when I run GUI, our USB3 open-ephys board and the ADC channel were detected, but the RHD2132 headstage were not. Hitting rescan did not help. Swapping with another openEphys board or headstage didn't help either. So I reckon it was a software issue as the Windows kept asking me to update some softwares and a new security app popped out (Microsoft Defender SmartScreen). I went to the debug console but dont know what to do with it
![PXL_20210717_200705017](https://user-images.githubusercontent.com/16696523/126080075-ac880ca5-72e1-4286-b8f2-0189e955768d.jpg)
![PXL_20210718_183415034](https://user-images.githubusercontent.com/16696523/126080090-3647f2f9-5e38-4e4b-b577-4b3cbab2b5cc.jpg)
![PXL_20210718_183454471](https://user-images.githubusercontent.com/16696523/126080098-0f5fe67f-f013-4f60-9b25-fca7d643e5ae.jpg)
![PXL_20210718_183345576](https://user-images.githubusercontent.com/16696523/126080104-9e6d64e6-88df-4ef6-b6f7-159630ddab4f.jpg)
![PXL_20210717_200656512](https://user-images.githubusercontent.com/16696523/126080173-2c33ee2b-ff43-4a13-a2c0-a55df1cd0103.jpg)

Could anyone suggest me what I should do?

Best Regards
Chi-Yu

**Comment by chiyu1203** [comment]
Hi everyone, sorry we fixed the issue. It was because of the headstage cable. We changed to another headstage cable and it worked now. Does anyone know where we can buy a new headstage cable (we already have few starter kits so just want to buy a cable)?

**Comment by jsiegle** [comment]
Glad you solved it!

You can buy individual cables from Intan, in either the standard or ultra-thin widths: https://intantech.com/pricing.html
