### ISSUE TITLE
PXI Trigger input was not recorded

### ISSUE THREAD

**Issue by Linoki** [open-ephys/plugin-GUI#468]
Hi I am using the version 0.3.3-API7 for neuropix-PXI as plugin. When I use an external TTL as a synchronization signal for neuropixel and National instrument, I dont get the TTL recorded in the 385th LFP_SYNC channel. Connecting to the sma port only brings the TTL signal amplitude down in the national instrument.

Anyone knows how to get the TTL registered in neuropixel LFP?

![image](https://user-images.githubusercontent.com/34261720/129116719-a5777b9d-f5f6-42ae-9107-f36682c3eaaa.png)
![image](https://user-images.githubusercontent.com/34261720/129116739-da43b882-2e62-46aa-87bc-63343704709a.png)

**Comment by medengineer** [comment]
Hello,

It appears the Neuropixels-PXI plugin is not detecting the synchronization signal at all. Is the external TTL signal at least 5V? Are you able to see the TTL signal in the Neuropixels' LFPViewer without the National Instrument device connected? The sync signal should appear as yellow vertical bars when the signal goes high.

**Comment by jsiegle** [comment]
This sounds like a hardware issue. If it's still happening, please open a new issue in the [`neuropixels-pxi`](https://github.com/open-ephys-plugins/neuropixels-pxi) repository.
