### ISSUE TITLE
Inconsistent file prefixes for the OpenEphys file format

### ISSUE THREAD

**Issue by SamMinkowicz** [open-ephys/plugin-GUI#477]
Hey, I am saving data in the OpenEphys format and the file prefixes are varying between recording sessions. The files from some sessions have the CH prefix while the files from other sessions don't. I'm using GUI v0.5.5.

This isn't a critical issue but would be nice to have fixed.

Thanks for making this software!

Best,
Sam

**Comment by jsiegle** [comment]
Hi Sam, thanks for pointing this out! This will definitely be fixed in the next release.

**Comment by jsiegle** [comment]
This has now been fixed.
