### ISSUE TITLE
v0.5.5.3 will generate 1Hz pulse

### ISSUE THREAD

**Issue by sppmg** [open-ephys/plugin-GUI#485]
Hi
I connect signal terminal (MultiClamp 700B output) to ADC_1 and also connect to oscilloscope.
When I play/record on open-ephys, oscilloscope will show some pulse (and maybe it's a pulse train).
*(Note, also happened when ADC_1 only connect to oscilloscope)*
![waveform](https://user-images.githubusercontent.com/6098465/141432345-898a68a4-3be3-489d-b60f-54f34beb9b0f.jpg)

That reminds me the voltage spikes from inductive. **But this pulse will not generate when I use `v0.4.6` in same connection.**

Oh, and this pulse will fast generation when measuring impedance.

------- 

# Some spectrogram (10KHz, ~5sec):
## open-ephys recording (ADC_1, to oscilloscope):
![adc_1](https://user-images.githubusercontent.com/6098465/141433315-4fbf13f8-3b4d-49d7-9514-3ed61e12a5f0.png)
It's nothing in spectrogram, but it's will show on oscilloscope and open-ephys `LFP-viewer`, just smaller. 

## open-ephys recording (ADC_8, float/no connection):
![adc_8](https://user-images.githubusercontent.com/6098465/141433389-eae65116-0a8f-4c1d-b26c-134da74a17e0.png)

## open-ephys recording (ch_7, probe channel, few channel has some effect.):
![ch_7](https://user-images.githubusercontent.com/6098465/141433433-feef247b-743e-4eb8-a95d-36678c6ff0c1.png)

**Comment by jsiegle** [comment]
Hi @sppmg, thanks for documenting this. Based on the images you've shown, it doesn't seem like there's any obvious contamination in the recorded data. The 1 Hz artifact is clear in the floating ADC channel, but this won't matter for an actual experiment.

Can you check whether the voltage spikes measured with the oscilloscope go away when you disable the LEDs on the acquisition board? There is a button to toggle this within the Rhythm FPGA plugin editor.

@aacuevas, are the any other changes in the bitfiles that could explain the difference between v0.4.6 and v0.5.5.2?

**Comment by aacuevas** [comment]
My guess would be cross-signal from the HARP output we added recently. It is sent through the i2c lines, so there could be coupling with some nearby channels. I also checks with this pulse being generated every second.

**Comment by sppmg** [comment]
Hi
Yes, I did turn off  LED, same result. No any difference (amplitude or
frequency).

And in my memory, spike also show in oscilloscope, even if it's no in
recording. (Maybe the spike source after ADC module/block? It's just my
guess.) It may affect another device which connect together.

Aarón Cuevas López ***@***.***> 於 2021年11月16日 週二 上午6:04 寫道：

**Comment by sppmg** [comment]
I will check again about does spike affect on connect together device.
(It's doesn't see in real *animal* experiment on yesterday. Previous testing experiment use saline.)

**Comment by jsiegle** [comment]
It seems like this artifact is benign...if it does seem to be affecting your experimental data, please re-open this issue.
