### ISSUE TITLE
Inclusion consideration of branch naming

### ISSUE THREAD

**Issue by wagenadl** [open-ephys/plugin-GUI#489]
The name “master” for a branch in a git repository is considered less inclusive than the more neutral “main”. Renaming the main branch to follow contemporary best practice would seem to be in line with the goals stated in the “code of conduct”.

**Comment by jsiegle** [comment]
Hey Daniel! We totally agree...when we put out the next release (v0.6.0) we will switch to `main` and will archive the current `master` branch under a different name. We will do the same for all the plugin repos as well.

**Comment by jsiegle** [comment]
The latest version of the GUI now lives on the `main` branch.
