### ISSUE TITLE
Build process fails in make step if dependencies are not present on linux

### ISSUE THREAD

**Issue by wagenadl** [open-ephys/plugin-GUI#490]
The build process fails during "make" when certain header files are missing. These dependency failures are not noticed by CMake during the configuration step.

Specifically:

- ALSA headers: alsa/asoundlib.h [libasound2-dev]
- Freetype headers: ft2build.h [libfreetype-dev]
- X headers:
   - X11/extensions/Xrandr.h [libxrandr-dev]
   - X11/extensions/Xinerama.h [libxinerama-dev]
   - X11/Xcursor/Xcursor.h [libxcursor-dev]

(Names in square brackets are the .deb packages that resolve the issues.)

I am using open-ephys plugin-GUI version v0.5.5.3 (commit dbe5892d2cb74f851503f667edbad056f71ebb83) on Ubuntu 20.04.

**Comment by anjaldoshi** [comment]
Hi Daniel,

When compiling the GUI from source on Linux, you need to install the dependencies before running CMake as mentioned in the wiki [over here](https://open-ephys.github.io/gui-docs/Developer-Guide/Compiling-the-GUI.html#linux). The `install_linux_dependencies.sh` script installs all the dependencies the GUI requires including the ones you mentioned above.
