### ISSUE TITLE
open .ns6 files

### ISSUE THREAD

**Issue by fabriziograni** [open-ephys/plugin-GUI#503]
Can we open an ns6 file recorded from the cerebus blackrock system through open ephys? I was not able to find information about this

**Comment by jsiegle** [comment]
Hi Fabrizio – the Open Ephys GUI doesn't support Blackrock files. I'd recommend taking a look at the [Neo package](https://neo.readthedocs.io/en/stable/), which can read data in a variety of formats, including Blackrock.
