### ISSUE TITLE
TTLs not faithfully recorded on linux version

### ISSUE THREAD

**Issue by fmarbach** [open-ephys/plugin-GUI#506]
I am saving frame TTLs from 4 cameras to the digital input of the open ephys board.
Summary of problem: A single camera works, 2 cameras sort of, 3-4 cameras tend to show frequent gaps across all digital inputs (see plot titled "Timestamps of all channels"). A function generator records very faithfully alone (100hz square wave), but when acquired together with 2 cameras shows gaps as well. **In the GUI, TTLs display fine, without gaps.** The only thing that helped was switching to a windows machine.
Details:
- Ubuntu 20.04.4 LTS
- Open ephys gui v0.5.5.3
- Data is saved in binary, loaded using the open-ephys/open-ephys-python-tools
- This did not help: Updating ubuntu, open ephys gui, switching computer, recording to analog input
![image](https://user-images.githubusercontent.com/7504735/157275064-a01248f9-39d9-42d6-99c0-0f008e05596d.png)
![image](https://user-images.githubusercontent.com/7504735/157275292-92c2a0a7-55e8-441b-afcb-82a34aa1dfc3.png)

**Comment by anjaldoshi** [comment]
Closing as it is fixed in [v0.5.5.4](https://github.com/open-ephys/plugin-GUI/releases/tag/v0.5.5.4).
