### ISSUE TITLE
OpenEphys digital desynchronizing over time

### ISSUE THREAD

**Issue by ClaraBesserer** [open-ephys/plugin-GUI#507]
Hello,

I've notice that my OpenEphys digital (and presumably headstage too) data desynchronize from 'real time'/Spike2 over time.

I use OpenEphys with eCube plugins, on windows 10. I record the data in Binary format. TTL are send by Spike2 and copied on a digital channel. When I try to match the two, I observe a somewhat linear desynchronization, at the rate of 0.8ms every 100ms (varies between recordings, can go from 0.81 to 0.89). After 2500s of recording it amounts to 20ms, so it's not negligeable (The digital OE data is late compared to the Spike2 data).

As an example, here are the first 50 TTL times from Spike2 (1 TTL every 0.5s) : 
array([12.2534, 12.7534, 13.2534, 13.7534, 14.2534, 14.7534, 15.2534,
       15.7534, 16.2534, 16.7534, 17.2534, 17.7534, 18.2534, 18.7534,
       19.2534, 19.7534, 20.2534, 20.7534, 21.2534, 21.7534, 22.2534,
       22.7534, 23.2534, 23.7534, 24.2534, 24.7534, 25.2534, 25.7534,
       26.2534, 26.7534, 27.2534, 27.7534, 28.2534, 28.7534, 29.2534,
       29.7534, 30.2534, 30.7534, 31.2534, 31.7534, 32.2534, 32.7534,
       33.2534, 33.7534, 34.2534, 34.7534, 35.2534, 35.7534, 36.2534,
       36.7534]) * s

And here are the same TTLs from OpenEphys:
array([12.2534 , 12.7534 , 13.2534 , 13.7534 , 14.25336, 14.75336,
       15.25336, 15.75336, 16.25336, 16.75336, 17.25336, 17.75336,
       18.25336, 18.75336, 19.25336, 19.75332, 20.25332, 20.75332,
       21.25336, 21.75332, 22.25332, 22.75332, 23.25332, 23.75328,
       24.25328, 24.75328, 25.25328, 25.75328, 26.25328, 26.75328,
       27.25328, 27.75328, 28.25332, 28.75324, 29.25324, 29.75324,
       30.25324, 30.75328, 31.25324, 31.75324, 32.25324, 32.75324,
       33.25324, 33.7532 , 34.2532 , 34.7532 , 35.2532 , 35.7532 ,
       36.25324, 36.7532 ])

As you can see, the shift in OpenEphys is not even constant. But if I plot the difference between the TTLs from Spike2 and OE, I get something that is relatively linear:
![shift_229_09_07](https://user-images.githubusercontent.com/87136903/165334809-046c132f-2481-47fb-94d0-2185e839bc3c.png)
The fitted orange line has a coef of 8.15e-6 (hence the 0.8ms every 100s I wrote above).

I believe that the headstage data has the same shift, because I observed a shift in neuronal response to certain events across a session. It's not a very big deal, I can correct the shift by multiplying the spike times, but I thought I'd notify you about this problem.

Has anybody else seen something similar? It might be a problem on our end, notably:
- It could come from the eCube itself, or the eCube OE plugins
- The data is transmitted from the eCube to the computer running OE via wifi, maybe it's too slow?

Best wishes,
Clara

**Comment by jsiegle** [comment]
Hi Clara – this seems like it's most likely an issue with either the eCube hardware or plugin...I'd recommend reaching out to White Matter support about this.
