### ISSUE TITLE
Very High ( 50KHz-4MHz) Inconsistent Impedance in EEG

### ISSUE THREAD

**Issue by spygaurad** [open-ephys/plugin-GUI#509]
@jsiegle @anjaldoshi Can you help me with this?
I am getting very high impedance in my EEG setup (AC current). 
The components of my EEG setup include: EEG acquisition board (open ephys), amplifier/ADC (open-ephys) and  electrodes and breakout board (Easy Cap).

I have used alcohol to clean and conducting paste on electrodes to get better result. The impedance is never going below 10kHz as required. 

I have connected pin 22, reference and ground to collect this impedance data.

Is there anything wrong with my setup?
(Used Rhythm FPGA to measure impedances.)
![image](https://user-images.githubusercontent.com/16435245/171135775-2a9df030-38fb-455b-9e31-fcb3e3205b03.png)

**Comment by jsiegle** [comment]
Hi @spygaurad – I don't have much experience with human EEG, but I can try to help. 

First of all, are the electrodes connected to ground via a conductive solution or someone's scalp? If they are just sitting in air then very high impedance values are expected.

**Comment by spygaurad** [comment]
Thanks @jsiegle for your response. For collecting this data, i have connected electrode 22(channel 22), the ground electrode and the reference electrode on scalp along with conductive solution. These electrodes are connected to EEG breakout board's port 22, GND and REF respectively. The remaining electrodes are on air.

**Comment by jsiegle** [comment]
Closing for now; if you're still experiencing this problem, please re-open this issue.
