### ISSUE TITLE
FileReader doesn’t load text events

### ISSUE THREAD

**Issue by simonoxen** [open-ephys/plugin-GUI#529]
Hi, thanks for the great software!

This is more of a feature request that I also mentioned a while back in the [google groups forum](https://groups.google.com/g/open-ephys/c/BzMnZ6fGGnk).

I use text events to handle data from my custom [device thread plugin](https://github.com/netstim/OpenEphysNeuroOmega). Would be great to be able to replay them after saving the session (as well as to create sample datasets containing such events).

I already implemented this in my fork: [https://github.com/simonoxen/plugin-GUI/tree/load_txt_events](https://github.com/simonoxen/plugin-GUI/tree/load_txt_events), and is currently working. However, when collaborating with others, this becomes more cumbersome.

Let me know if you are interested in a PR or if I can provide some more help to make this happen.

Thanks!

**Comment by jsiegle** [comment]
Can you submit a PR for this? We are planning to do a new release before SfN, it might not make it in before then. But we will test this out and hopefully include it in the next one!

**Comment by simonoxen** [comment]
Thanks! Just did #530
