### ISSUE TITLE
LFP Viewer plot discontinuity at low sampling rates

### ISSUE THREAD

**Issue by florin-pop** [open-ephys/plugin-GUI#532]
Hello,
I've recently started working on a plugin for `open-ephys` and I noticed a strange behaviour with signals that have a low sampling rate (around 100Hz), specifically there are discontinuities in the waveform.
The behaviour can be reproduced with the `File Reader` by loading this [sample data](https://github.com/open-ephys/plugin-GUI/files/10024935/2022-11-16_19-59-21.zip) which contains 472 samples and 4 channels, each sample has a constant value (0.97uV for channel 1, approx. 2 uV for channel 2 and so on).  The expectation is to see a continuous line in the LFP plot, but it's often an interrupted line. 
<img width="2024" alt="Screenshot 2022-11-16 at 20 03 01" src="https://user-images.githubusercontent.com/13623704/202272667-9a830c8e-a568-41f9-87aa-fea04e674276.png">
This behaviour is accentuated for more complex signals and they look broken. When the sampling rate is 1kHz or higher I didn't notice the any issues.
I was trying to investigate if I am doing something wrong and started the GUI with the debugger and noticed some assertions failing in a buffer associated with LFP. Could this be a limitation or a bug with `open-ephys`? 
<img width="2032" alt="Screenshot 2022-11-16 at 20 01 55" src="https://user-images.githubusercontent.com/13623704/202273977-5f9977c5-74af-4de8-a2d0-355fc0493b30.png">

**Comment by jsiegle** [comment]
It looks like adding a `continue` statement after updating `lastIndex` avoids the assertion and fixes the display glitch:

https://github.com/open-ephys/plugin-GUI/blob/8a18e3a1864b7d0fa2a831b9495a042c398f4c06/Plugins/LfpDisplayNode/LfpDisplayCanvas.cpp#L1231-L1235

If that works on your end, we will include this change in the next release!

**Comment by florin-pop** [comment]
@jsiegle thank you for looking into this. I can confirm that your suggestion does indeed fix the problem. I also tested it with a heartbeat stream and it worked well. This issue can be closed.
