### ISSUE TITLE
Can not detect Intan board

### ISSUE THREAD

**Issue by orena1** [open-ephys/plugin-GUI#540]
Hi,
Maybe I am missing something, but it seems that the gui can not detect my Intan board, 
e.g.

![image](https://user-images.githubusercontent.com/8983713/207081091-553e1eee-f8dc-411f-a498-b1b82e90cb32.png)

Am I doing something wrong?

This is what I see in the logs:
![image](https://user-images.githubusercontent.com/8983713/207082225-68e7d8f0-0af6-438c-9be3-09262ad9b471.png)

It is a fresh installation directly from the website

**Comment by jsiegle** [comment]
Hi there – it looks like our plugin database went down temporarily, but it's back up now. You should be able to install the "Rhythm Plugins" now, which will add the Acquisition Board plugin to the processor list.

**Comment by orena1** [comment]
Thanks!
Working now
