### ISSUE TITLE
Can not open plugins menu

### ISSUE THREAD

**Issue by orena1** [open-ephys/plugin-GUI#541]
Hi,
When I open the plugins menu, I see a small box but I can not use it to install any plugin:
![image](https://user-images.githubusercontent.com/8983713/207081885-bba73552-e479-4773-8489-b438ce1c3609.png)

Any way to troubleshoot it? 

This is what I see in the logs:
![image](https://user-images.githubusercontent.com/8983713/207082186-d8f0c0ec-715e-4cd1-8404-a1b555661223.png)

**Comment by jsiegle** [comment]
This is the same problem as #540...the plugin database went down temporarily, but it's back up now. If you launch the Plugin Installer again, it should work.

**Comment by orena1** [comment]
Got it, thanks a lot!
