### ISSUE TITLE
Incorrect restoration of record state

### ISSUE THREAD

**Issue by beOn** [open-ephys/plugin-GUI#55]
Here's what I'm seeing.

Steps (with a headstage attached):
- Start with a blank setup
- Add a Rhythm FPGA processor
- Disable recording for all but the first three headstage channels (so REC->none, then click 1,2 and 3)
- Enable ADC channels
- Enable recording for all ADC channels
- Save your config
- Quit, come back, load your config

Expected:
The first three headstage channels and the last eight should be set to record.

Observed:
The first three headstage channels, first three AUX channels, and first three ADC channels are set to record.

I tracked it down to GenericProcessor::update(). If you wind up generating new settings, then you wind up going through the following for loops:

``` c++
for (int i = 0; i < getNumHeadstageOutputs(); i++)
```

``` c++
for (int j = 0; j < getNumAuxOutputs(); j++)
```

``` c++
for (int k = 0; k < getNumAdcOutputs(); k++)
```

These respectively set channel's recording status as follows:

``` c++
if (i < recordStatus.size())
{
    ch->setRecordState(recordStatus[i]);
}
```

``` c++
if (j < recordStatus.size())
{
    ch->setRecordState(recordStatus[j]);
}
```

``` c++
if (k< recordStatus.size())
{
    ch->setRecordState(recordStatus[k]);
}
```

In light of the use of i, j and k here, the observed behavior makes sense. The first three channels in recordStatus are set to record, so the the first three channels of each type will be set to record.

The issue goes away if I use nidx, which tracks the cumulative channel index, rather than i, j and k.

I'll submit a PR after lunch.

**Comment by kylerbrown** [comment]
Thanks for this! I've also experienced this bug.
