### ISSUE TITLE
Open Ephys Gui interface opens at left side of screen and cannot be accessed 

### ISSUE THREAD

**Issue by LaurensGoyvaerts98** [open-ephys/plugin-GUI#579]
WTF is this shit. Ever since i bought the new acquisition board, nothing seems to work anymore

**Comment by anjaldoshi** [comment]
We are aware of the issue causing the GUI to go out of screen bounds sometimes. This can happen when the monitor configuration of the system running the GUI changes between sessions. 
As mentioned in this issue  https://github.com/open-ephys/plugin-GUI/issues/573, we've already identified the issue and pushed a fix for it on the development branch. It will get merged in the next release.

Till then, you can follow the instructions on the issue I linked above to get the window back into the screen bounds. If that doesn't work, you can simply remove the `windowState.xml` file from `C:\ProgramData\Open Ephys\configs-api8` (ProgramData is a hidden system directory), and relaunch the GUI after that.
