### ISSUE TITLE
GUI crashes every run

### ISSUE THREAD

**Issue by gabrielstine** [open-ephys/plugin-GUI#581]
Hello,

I just setup a new acquisition board and finding that the gui crashes on every single run within a few minutes. Up until the crash everything seems to be working properly. Below is the output of the command window for the most recent crash.

Thanks,
Gabe

[open-ephys] Session Start Time: 25 Jul 2023 13:53:37
[open-ephys] Open Ephys GUI v0.6.5 (Plugin API v8)
[open-ephys] JUCE v6.0.8
[open-ephys] Operating System: Windows 10
[open-ephys] CPU: Intel(R) Xeon(R) W-2225 CPU @ 4.10GHz (8 core)
[open-ephys] Audio device name: Speakers / Headphones (Realtek Audio)

[open-ephys] Audio device type: Windows Audio
[open-ephys] Audio output channels: 2
[open-ephys] Audio device sample rate: 44100
[open-ephys] Audio device buffer size: 1024

[open-ephys] Beginning HTTP server on port 37497
[open-ephys] Creating processor with name: OE FPGA Acquisition Board
[open-ephys] Open Ephys ECP5-ONI FPGA open. Gateware version v1.0
[open-ephys] Creating processor with name: LFP Viewer
[open-ephys] Adding audio callback.
Read failure 32
[open-ephys] ***ERROR*** Error reading ONI frame: Failure to read from a stream or register code -5
[open-ephys] ***ERROR*** Aquisition error...stopping thread.
[open-ephys] ***ERROR*** Notifying source node to stop acqusition.

**Comment by jsiegle** [comment]
Hi Gabe – can you confirm you have the board connected to a USB 3.0 port?

**Comment by gabrielstine** [comment]
Yes, it is connected to USB 3.0. I had an arduino running in the background
on the same PC. Unplugging the arduino and then plugging it back in seemed
to have fixed the problem. Strange!

Gabe

**Comment by jsiegle** [comment]
Yeah, there are sometimes strange interactions on the USB bus. Glad that fixed it!
