### ISSUE TITLE
Recording stopping due to negative remaining disk space

### ISSUE THREAD

**Issue by spencerblackwood** [open-ephys/plugin-GUI#585]
I am using GUI v0.6.5.

My recordings are sporadically stopping, and I am getting a warning that I don't have enough recording space left on the drive. The tooltip on the record node says that I have a negative amount of time left before the disk is full. I assume that there's an int overflow occurring and the number goes negative. Pic attached

![disk_space_issue](https://github.com/open-ephys/plugin-GUI/assets/42746356/7b3e1c96-fd3d-4f33-b180-dcdf47b8f4c1)

**Comment by jsiegle** [comment]
That's exactly right. I just [pushed the fix to `development`](https://github.com/open-ephys/plugin-GUI/commit/2043baade66177f24af4d0a617575b469cb839ff)...we are planning to do a new release this week, this will definitely get included.
