### ISSUE TITLE
Maximizing the Beta LFP crashes GUI with JUCE Assertion failure in juce_Image.cpp:395

### ISSUE THREAD

**Issue by jonnew** [open-ephys/plugin-GUI#59]
OS: Ubuntu 14.04
OE Version: 94771673fec1f55bd84acde1a586506b91ecabdb

To reproduce, while OE GUI is running
1. Press the box on the Beta LFP viewer plugin tab to open as separate window
2. Try to maximize window

OE crashes with infinite

```
JUCE Assertion failure in juce_Image.cpp:395
```

**Comment by jsiegle** [comment]
Just tested on Ubuntu 18.04, and didn't see this issue. I assume this was fixed a while ago.
