### ISSUE TITLE
Subject: Assistance with Minicam and DAQ-Miniscope Configuration

### ISSUE THREAD

**Issue by Alberto100591** [open-ephys/plugin-GUI#595]
Hello,

My name is Alberto Lopez. I am reaching out to request assistance with my Minicam system (https://open-ephys.org/minicam/minicam), which I purchased along with the DAQ-Miniscope (https://open-ephys.org/miniscope-daqs/daq). My goal is to record videos and store them. Currently, I have the system set up and connected (Minicam connected to the DAQ-Miniscope). However, I am unsure about which .json file I should load to initiate the recording. I would greatly appreciate your guidance on this matter.

Thank you for your attention!

Best regards,
Alberto Lopez

**Comment by jsiegle** [comment]
Hi @Alberto100591 – I'm closing this issue since it's not related to the Open Ephys GUI, and there's a separate email thread with the support team. We will help you figure out the right approach!
