### ISSUE TITLE
Distributing FTDI driver v1.3.0.8 with the GUI

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/plugin-GUI#598]
[Installers included in the GUI](https://github.com/open-ephys/plugin-GUI/blob/6111d120968eb5f336769b4e8366f17637bc682e/Resources/Installers/Windows/windows_installer_script.iss#L29) point to FTDI driver version 1.3.0.4, but they are now on version 1.3.0.8. Problems originally caused by driver version 1.3.0.8 are [resolved](https://github.com/open-ephys/ECP5U85-BSE-USB/issues/3) in OE FPGA Acquistion Board plugin v 0.2.3.

Is this stable enough to package driver version 1.3.0.8 with the GUI?

**Comment by jsiegle** [comment]
@aacuevas what are your thoughts on this?

**Comment by aacuevas** [comment]
It should be ok to go ahead and distribute the newer driver

**Comment by anjaldoshi** [comment]
Done in https://github.com/open-ephys/plugin-GUI/commit/4b8408e46752425c8c2a245acad9e3482f8cfae6.
New downloads of GUI v0.6.6+ for Windows are now packaged with driver v1.3.0.8
