### ISSUE TITLE
Some values are impossible to select in the PARAM Grid

### ISSUE THREAD

**Issue by jonnew** [open-ephys/plugin-GUI#61]
OS: Ubuntu 14.04
OE Version: 9477167

Some channels cannot be accessed by scrolling on the side tab "PARAM" tables. For instance, look at the PARAM table for the LFP viewer in the top most position:

![2016-06-21-181513_1898x1073_scrot](https://cloud.githubusercontent.com/assets/1429475/16248606/243c03a8-37de-11e6-91e8-70a585de4877.png)

If I scroll, the table advances by more than two rows. This means that there are rows (e.g. 13 -17 in these images) that are not accessible for selection by clicking.

![2016-06-21-181519_1898x1073_scrot](https://cloud.githubusercontent.com/assets/1429475/16248589/166bdbae-37de-11e6-842f-ad577f8b9efa.png)

IMO, all of this would be solved by using a standard list selection element analogous to the [QT combobox](http://doc.qt.io/qt-4.8/qcombobox.html) instead of the custom tables. These elements also come with a great deal of sanity checking capabilities so you don't have to roll your own.

**Comment by sept-en** [comment]
Hi!

We've already solved it in the **development** branch, the element with buttons was reimplemented and also we added possibility to hide the components for selecting the channels using slice format (textbox at the top and '+', '-' buttons).

I guess these changes will be merged into master in the new release version of Open-Ephys GUI.

Best regards,
Kirill Abramov.

**Comment by jonnew** [comment]
OK, but of course, the + and - buttons, along with selecting groups of channels with the textual syntax have been _solved_ in a standard combobox. Why not use the standard solution? It even looks like JUCE has one

https://www.juce.com/doc/classComboBox#details

I would push for ditching these grids of channels in favor of comboboxes. They are much more flexible IMO and come with lots of functionality packed in that we should not have to recreate. 

Additionally, I've experienced some strangeness when selecting channles in the channel map component that may be related. When I try to drag a channel that is > 64, the mouse must hover beneath all the channel numbers (like where the channel would have been located _before_ I scrolled the grid down). Look at this image

![2016-06-21-153343_1904x1070_scrot](https://cloud.githubusercontent.com/assets/1429475/16251613/8ce49b74-37f5-11e6-972b-14b518021201.png)

My mouse does not show up in the screenshot, but you can see its position which is at the hovering `89`. You can see where this channel will be inserted if I was to release the left mouse button in the grid way above where the mouse is. Additionally, you can see an extra row of numbers shooting out the top of the grid.

**Comment by aacuevas** [comment]
Juce's ComboBoxes are just drop-down selectors (with an optional text input), they do not allow the selection of multiple, random values (which is sometimes required in the param tab, but always in the record one) nor can they display channels in a nice grid-based way. I'm not sure if there is any Juce pre-made component that could work for the channel selectors, but it's worth checking. (Although don't keep your hopes high. With Juce its relatively easy to create UI components, but it itself only has a very scarce handful of them pre-made).

The channel mapper one is a completely separate issue, probably some bad index in the drag&drop code. I'll check it too.

**Comment by jonnew** [comment]
OK, I will open a separate issue for it.
