### ISSUE TITLE
Events are not being saved for multiple datasets in Kwik

### ISSUE THREAD

**Issue by malfatti** [open-ephys/plugin-GUI#63]
I'm using multiple datasets recordings. After running some tests, I noticed that the events are not being saved for all datasets, only for the last one. I recorded  8 datasets, each should have four events (two TTL pulses).

Steps I followed:
- Connected a 16Ch headstage, two ADC channels and two TTL channels;
- Added FPGA, RecordControl and LFPViewerBeta modules to signal chain;
- Activated ADCs and changed 32 to 16ch in FPGA module;
- Set FPGA module to record only channels 1, 20 and 21 (one from headstage and two from ADCs);
- Set RecordControl to Edge toggle, Ch8, Rising;
- Set to save as Kwik and set path;
- Play;
- Used TTLs on digital input 8 to start and stop recordings

Actual result:
A .kwe with event info only from the last dataset (other files are ok).

``` python
In [1]: import h5py

In [2]: FileName = 'KwikFiles/2016-06-22_14-04-26/experiment1.kwe'

In [3]: F = h5py.File(FileName, 'r')

In [4]: list(F['recordings'])
Out[4]: ['0', '1', '2', '3', '4', '5', '6', '7']

In [5]: list(F['event_types']['TTL']['events']['recording'])
Out[5]: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
```

Expected results (for example, a recording I did months ago):
A .kwe with all event info from all datasets (between other files).

``` python
In [6]: X = h5py.File('../../KwikFiles/2016-03-29_17-16-56/experiment1.kwe', 'r')

In [7]: list(X['recordings'])
Out[7]: ['0', '1', '2', '3', '4', '5', '6', '7']

In [8]: print(list(X['event_types']['TTL']['events']['recording']))
[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7]
```

In both recordings I recorded 1 headstage channel + 2 ADC channels. The TTL channels used were also the same.

If I `git clone https://github.com/open-ephys/plugin-GUI`, `git reset --hard 723b328` (a random commit from 28/03/2016) and compile, then events are saved as expected.

Cheers :)

**Comment by jsiegle** [comment]
The KWIK format code now lives here: https://github.com/open-ephys-plugins/kwikformat

The latest version is correctly saving events for multiple recordings.
