### ISSUE TITLE
Crash when GUI is closed after loading a processing chain for which the headstage is not present

### ISSUE THREAD

**Issue by jonnew** [open-ephys/plugin-GUI#64]
OS: Ubuntu 14.04
OE Version: 9477167
- Open the GUI
- Load a previous processing chain (attached below), but don't have the appropriate headstages attached to the OE board. For this reason, the processing chain is greyed out. This is fine.
- Close the GUI window using `X` button
- Receive

```
Filters/Spike Sorter
Create subnodes with parameters
  Moving forward along signal chain.
Sinks/Spike Viewer
Create subnodes with parameters
  Moving forward along signal chain.
  No processor found.
   Processor already saved as number 5
  Moving forward along signal chain.
Sinks/LFP Viewer
Create subnodes with parameters
  Moving forward along signal chain.
  No processor found.
  End of chain.
*** Error in `./open-ephys': munmap_chunk(): invalid pointer: 0x000000000f98cca0 ***

[1]+  Stopped                 ./open-ephys
```
- OE GUI is stopped in background. I must be brought forward using `fg` and killed using `SIGQUIT`

Signal chain:

[adjustment_00.zip](https://github.com/open-ephys/plugin-GUI/files/328641/adjustment_00.zip)

**Comment by jsiegle** [comment]
This should be fixed in the latest version of the GUI. If it's still happening, please re-open this issue.
