### ISSUE TITLE
Mouse pointer location offset for large channel counts in channel mapper component

### ISSUE THREAD

**Issue by jonnew** [open-ephys/plugin-GUI#65]
OS: Ubuntu 14.04
OE Version: 9477167

**Note**: Moved from #61 

I've experienced some strangeness when selecting channels in the channel map component that may be related. When I try to drag a channel that is > 64, the mouse must hover beneath all the channel numbers (like where the channel would have been located before I scrolled the grid down). Look at this image

![8ce49b74-37f5-11e6-972b-14b518021201](https://cloud.githubusercontent.com/assets/1429475/16286668/f4fd5b72-38ab-11e6-8c54-54dfbfd06b23.png)

My mouse does not show up in the screenshot, but you can see its position which is at the hovering 89. You can see where this channel will be inserted if I was to release the left mouse button in the grid way above where the mouse is. Additionally, you can see an extra row of numbers shooting out the top of the grid

**Comment by jsiegle** [comment]
This issue was solved by the latest pull request from @godwincharan.
