### ISSUE TITLE
Absolute paths in JuliaProcessor prevent compilation

### ISSUE THREAD

**Issue by galenlynch** [open-ephys/plugin-GUI#80]
I am unable to compile the development branch on Ubuntu 16.04.1 LTS 64-bit due to the JuliaProcessor plugin using absolute paths to specify locations.

Here is the error I get when I attempt to build the plugins:

```
Compiling JuliaEditor.cpp
Building JuliaProcessor.so
g++: error: /home/jvoigts/Documents/Github/julia//usr/lib: No such file or directory
```
There are references to `/home/jvoigts...` in at least three files:
```
~/D/C/p/S/P/JuliaProcessor ❯❯❯ grep -rl /home/jvoigts ./
Makefile
JuliaEditor.cpp
JuliaProcessor.cpp
```

**Comment by jvoigts** [comment]
yup this plugin is very much still in progress and not usable as is - you can remove it from your fork or not compile it. I've been meaning to get this buttoned up for a while now, maybe one of these weekends i'll clean this up and make it work at least with some very basic functionality.
