### ISSUE TITLE
Digital fast settle command not working in windows

### ISSUE THREAD

**Issue by mich11** [open-ephys/plugin-GUI#98]
Hi, 

I'd like to command the headstage (RHD2132 16-channel from Intan) to fast settle after a stimulation artifact that appears to saturate headstage output.  When I set a digital input channel to control the TTL fast settle in the rhythm FPGA source on the open ephys GUI and provide a digital input through this channel with the pulse pal, amplifier output remains unchanged, but the digital input is detected and reported as an event by the GUI.  I'm running Windows 7 enterprise; running the GUI as an administrator didn't change performance.  Is there something else I need to do to control the fast settle command for our headstage? 

Thanks very much,
Michelle

**Comment by jsiegle** [comment]
The plugin for interfacing with the acquisition board now lives here: https://github.com/open-ephys-plugins/rhythm-plugins

If you're still experiencing this problem with the latest version of the GUI, please open an issue in that repository.
